# workflow name
name: sync-gitee

# master branch on push, auto run
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: 检查master分支
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: 部署页面
        run: |
          ls
          git init
          git config --global user.name '${{ secrets.GIT_USER }}' 
          git config --global user.email '${{ secrets.GIT_MAIL }}'
          git push --force --all https://${{ secrets.GITEE_TOKEN }}@${{ secrets.GITEE_REPO }}

      - name: 自动部署gitee
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: kkfive
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: kkfive/kkfive
